name = "Jurassic Gay"
author = "Lily"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b45a44a0a5a0ec199f5e18c33730cf5b805a3537c274ac1165d954a083e06fbc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
