name = "Jurassic Gay"
author = "Lily"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b5b50784e5bb9d51e35e51823b259c028db1a46cc15a467d30d9fb80909df7b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
